
name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
      - name: check nostd
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --no-default-features
      - name: test nostd
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features
      - name: check constrandom
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --no-default-features --features compile-time-rng
      - name: test constrandom
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features --features compile-time-rng
      - name: check fixed-seed
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --no-default-features --features std
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
  nightly:
    name: nightly
    runs-on: ubuntu-latest
    env:
        RUSTFLAGS: -C target-cpu=native
    steps:
      - uses: actions/checkout@v2 
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: clippy
      - name: check nightly
        uses: actions-rs/cargo@v1
        with:
          command: check